#!/bin/bash
#
# This file is part of Builder.
#
# Builder is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Builder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Builder.  If not, see <https://www.gnu.org/licenses/>.
#

URL=https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
SHA256SUM=4b0f07428ba854174c58d2e38287e5402964c9a9355f6c359d1242efd0990da3

build_package () {
	log_status ">>> no compile for binary distribution ${PACKAGE}/${VERSION}/${VARIANT}..."
	cd "${BUILD}"
	set -x
	cp -a ${SOURCE}/* .
	set +x
}

build_install () {
	log_status ">>> installing..."
	mkdir -pv ${TARGET}
	cp -a ${BUILD}/* ${TARGET} 2>&1 | tee "${LOG}/install.log"
}
