#%Module1.0#####################################################################
#
# ${PACKAGE}/${VERSION}/${VARIANT}
# ${AUTOMATIC_BUILD_WARNING}
#
set INSTALLDIR "${TARGET}"

proc ModulesHelp { } {
        global VERSION
        puts stderr "${PACKAGE} ${VERSION} (${VARIANT})"
}

module-whatis   "${PACKAGE} ${VERSION} ${VARIANT}"

conflict ${PACKAGE}
${PREREQ_DEPENDS}

prepend-path    PATH              "\$INSTALLDIR/"
